target 'CalendarForChatRecord' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WoWo
pod ‘Masonry’
pod 'ReactiveCocoa', '~> 2.5'


end